Repository serratus-bio/serratus.io, pull requests merged in 2020-08, with the labels that each got.

#59 Query: fix title fetching
  src/SDK/DataSdk.jsx
Labels: bug

#58 Feature/lohrd/paginator
  src/SDK/DataSdk.jsx
  src/components/Paginator.jsx
  src/components/QueryResult.jsx
  src/helpers/QueryPageHelpers.jsx
  src/pages/Query.jsx
Labels: enhancement

#61 Improve URL tracking
  src/App.jsx
  src/index.jsx
Labels: enhancement

#68 Add PR/issue templates, update docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  doc/explore-coronaviridae.png
  doc/query-frank.png
  doc/query-genbank.png
Labels: documentation

#71 Navbar: add preprint link
  src/components/Navbar.jsx
Labels: documentation, enhancement

#72 Explore, Query: add references to Access Data Release, preprint citation
  src/components/DataReference.jsx
  src/pages/Explore.jsx
  src/pages/Query.jsx
Labels: documentation, enhancement
